// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OPGAVESTYRINGSSYSTEM;

#nullable disable

namespace OPGAVESTYRINGSSYSTEM.Migrations
{
    [DbContext(typeof(OpgaveStyringsDBContext))]
    [Migration("20221013124137_ActualNewModelUpdate")]
    partial class ActualNewModelUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.TeamWorker", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkerId", "TeamId");

                    b.ToTable("TeamWorkers");
                });

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TodoId");

                    b.HasIndex("TaskId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("TeamWorker", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("workersWorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "workersWorkerId");

                    b.HasIndex("workersWorkerId");

                    b.ToTable("TeamWorker");
                });

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.Todo", b =>
                {
                    b.HasOne("OPGAVESTYRINGSSYSTEM.Model.Task", null)
                        .WithMany("Todos")
                        .HasForeignKey("TaskId");
                });

            modelBuilder.Entity("TeamWorker", b =>
                {
                    b.HasOne("OPGAVESTYRINGSSYSTEM.Model.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OPGAVESTYRINGSSYSTEM.Model.Worker", null)
                        .WithMany()
                        .HasForeignKey("workersWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OPGAVESTYRINGSSYSTEM.Model.Task", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
